[package]
name = "dm_reverb"
version = "0.1.0"
authors = ["davemollen <davemollen@gmail.com>"]
edition = "2021"

[dependencies]
lv2 = { git = "https://github.com/davemollen/rust-lv2.git", features = [
    "minimal_plugin",
] }
reverb = { path = "../reverb" }

[lib]
crate-type = ["cdylib"]
